---
- name: Установка необходимых пакетов
  package:
    name:
      - samba-client
      - krb5-workstation
      - oddjob-mkhomedir
      - pam_krb5
    state: present

- name: Настройка Kerberos на клиенте
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: Присоединение к домену
  command: net ads join -U Administrator%{{ domain_admin_password }}

- name: Настройка PAM для доменной аутентификации
  template:
    src: system-auth.j2
    dest: /etc/pam.d/system-auth
    owner: root
    group: root
    mode: 0644

- name: Настройка автоматического создания домашних директорий
  systemd:
    name: oddjobd
    state: started
    enabled: yes